# Config options: https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 3.0.6
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - '**/*.erb'
  Rails:
    Enabled: true

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
