origin: 'https://mmt.sit.earthdatacloud.nasa.gov'
headers:
  - Access-Control-Allow-Origin
  - Access-Control-Allow-Credentials
  - Access-Control-Request-Headers
  - Access-Control-Request-Methods
  - Authorization
  - Origin
  - User-Agent
allowCredentials: true
