name: PR check

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *' # daily

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true # runs `bundle install`
    - run: bundle exec rubocop .